# Exported from Render on 2025-08-01T23:48:34Z
services:
- type: web
  name: VCAT-Evidence-Repository
  runtime: docker
  repo: https://github.com/ck999kk/VCAT-Evidence-Repository
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: checksPass
version: "1"
