title: VCAT Evidence Repository
description: Professional legal evidence management system for Victorian Civil and Administrative Tribunal cases
baseurl: "/VCAT-Evidence-Repository"
url: "https://ck999kk.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  evidence:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .git/
  - README.md